# Site
title:              Chrome Controller
bio:                ''
description:        ''
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chromecontroller.com" # the base hostname & protocol for your site

# Urls
webstore_download_url: "https://chrome.google.com/webstore/detail/chrome-controller/nilnjekagachinflbdkanmblmjpaimhl"
repository_url: "https://github.com/McCrearyD/chrome-controller"
patreon_url: "https://www.patreon.com/chromecontroller"
supported_controllers_url: "https://html5gamepad.com/controllers/"
test_controllers_url: "https://html5gamepad.com/"
developer_guide_url: "https://github.com/McCrearyD/chrome-controller#developers"

# Comments
disqus_shortname:   default

# Social
analytics-id:       "UA-172247453-1"
twitter:            dyllan_ai
# facebook:           default
# instagram:          default
github:             mccrearyd

# personal
location:           CA
phone:              # 310-318-5555
email:              support@chromecontroller.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Dyllan McCreary

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
