name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.0.1
    - name: Build the site in the jekyll/builder container
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
